services:
  db:
    image: postgres:16
    container_name: shareit_db
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: shareit
      POSTGRES_PASSWORD: shareit
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shareit -d shareit"]
      interval: 2s
      timeout: 2s
      retries: 15
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: shareit_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shareit
      SPRING_DATASOURCE_USERNAME: shareit
      SPRING_DATASOURCE_PASSWORD: shareit
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_SQL_INIT_MODE: ALWAYS
      SPRING_SQL_INIT_ENCODING: UTF-8
      # Опционально: если хочешь переопределить логирование
      # LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_ORM_JPA: INFO
      # LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_TRANSACTION: INFO
      # LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_TRANSACTION_INTERCEPTOR: TRACE
      # LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_ORM_JPA_JPA_TRANSACTION_MANAGER: DEBUG

volumes:
  db_data:
