services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
      args:
        MVN_PROFILES: ""   # дефолт
    ports:
      - "9090:9090"
    environment:
      - TZ=UTC

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    depends_on:
      server:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      - TZ=UTC
