version: "3.9"

services:
  postgres:
    ports:
      - "5432:5432"

  shareit-server:
    network_mode: "host"
    environment:
      TZ: UTC
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/shareit
      SPRING_DATASOURCE_USERNAME: shareit
      SPRING_DATASOURCE_PASSWORD: shareit
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:9090/actuator/health | grep -q 'UP'"]
      interval: 5s
      timeout: 3s
      retries: 40

  shareit-gateway:
    network_mode: "host"
    environment:
      TZ: UTC
      SHAREIT_SERVER_URL: http://localhost:9090
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/actuator/health | grep -q 'UP'"]
      interval: 5s
      timeout: 3s
      retries: 40
