version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: shareit-postgres
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: shareit
      POSTGRES_PASSWORD: shareit
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shareit -d shareit"]
      interval: 5s
      timeout: 3s
      retries: 20

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
      args:
        MVN_PROFILES: ""   # дефолт
    container_name: shareit-server
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "9090:9090"
    environment:
      TZ: UTC
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shareit
      SPRING_DATASOURCE_USERNAME: shareit
      SPRING_DATASOURCE_PASSWORD: shareit
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:9090/actuator/health | grep -q 'UP'"]
      interval: 5s
      timeout: 3s
      retries: 40

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: shareit-gateway
    depends_on:
      server:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      TZ: UTC
      SHAREIT_SERVER_URL: http://server:9090
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/actuator/health | grep -q 'UP'"]
      interval: 5s
      timeout: 3s
      retries: 40
